# linear algebra

In [1]:
import numpy as np

# vectors

In [37]:
# vector define as a numpy array

In [38]:
v1 = np.array([10,15,20,25])

In [39]:
v1

array([10, 15, 20, 25])

In [40]:
v1.T

array([10, 15, 20, 25])

In [41]:
print(v1.T)

[10 15 20 25]


In [42]:
v1 = np.array([10,15,20,25],ndmin=2)

In [43]:
v1.T

array([[10],
       [15],
       [20],
       [25]])

In [44]:
v2 = np.random.randn(3,3)

In [45]:
v2

array([[ 0.22395987, -0.935583  ,  0.89009697],
       [-2.23835026, -1.24237823,  0.05203507],
       [ 0.08413775, -0.56727405, -1.20438599]])

In [46]:
v2.T

array([[ 0.22395987, -2.23835026,  0.08413775],
       [-0.935583  , -1.24237823, -0.56727405],
       [ 0.89009697,  0.05203507, -1.20438599]])

In [47]:
# adding 2 vectors

In [48]:
v1

array([[10, 15, 20, 25]])

In [49]:
v3 = np.array([2,4,6,8])

In [50]:
v1 + v3

array([[12, 19, 26, 33]])

In [51]:
# subtracting 2 vectors

In [52]:
v1 - v3

array([[ 8, 11, 14, 17]])

In [53]:
# scalar multiplication with vector

In [54]:
s = 2
v1

array([[10, 15, 20, 25]])

In [55]:
v1 * s

array([[20, 30, 40, 50]])

In [56]:
# * & dot product of 2 vectors

In [57]:
v4 = np.array([10,20])
v5 = np.array([25,6])

In [58]:
v4 * v5

array([250, 120])

In [59]:
np.dot(v4,v5)

370

# matrix

In [60]:
# method-1: create matrix by numpy array

In [61]:
m1 = np.array([[12,10],
               [4,6]])
m2 = np.array([[2,8],
               [46,63]])

In [62]:
# matrix addition & substraction

In [63]:
m1 + m2

array([[14, 18],
       [50, 69]])

In [64]:
m1 - m2

array([[ 10,   2],
       [-42, -57]])

In [65]:
# method-2: create matrix by matrix class

In [66]:
m3 = np.matrix("1 3 5;2 4 6; 1 4 8")

In [67]:
m3

matrix([[1, 3, 5],
        [2, 4, 6],
        [1, 4, 8]])

In [68]:
m4 = np.matrix([[1,3,5],[2,4,6],[1,4,8]])

In [69]:
m4

matrix([[1, 3, 5],
        [2, 4, 6],
        [1, 4, 8]])

In [70]:
# matrix addition & substraction

In [71]:
m3 + m4

matrix([[ 2,  6, 10],
        [ 4,  8, 12],
        [ 2,  8, 16]])

In [72]:
m3 - m4

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [112]:
# matrix multiplication by * & dot() are same

In [74]:
m3 * m4

matrix([[12, 35, 63],
        [16, 46, 82],
        [17, 51, 93]])

In [113]:
m5=m3.dot(m4)

In [114]:
m5

matrix([[12, 35, 63],
        [16, 46, 82],
        [17, 51, 93]])

In [ ]:
m1 * m1

In [77]:
np.transpose(m5)

matrix([[12, 16, 17],
        [35, 46, 51],
        [63, 82, 93]])

In [78]:
m5.T

matrix([[12, 16, 17],
        [35, 46, 51],
        [63, 82, 93]])

# linear equation

In [79]:
# linear equations with linalg module

In [115]:
m1

array([[12, 10],
       [ 4,  6]])

In [117]:
m2=np.linalg.inv(m1)
m1*m1

array([[144, 100],
       [ 16,  36]])

In [116]:
m6 = np.linalg.inv(m1)

In [82]:
m6

array([[ 0.1875, -0.3125],
       [-0.125 ,  0.375 ]])

In [83]:
# matrix power

In [84]:
m1

array([[12, 10],
       [ 4,  6]])

In [118]:
m7 = np.linalg.matrix_power(m1,2)

In [119]:
m7

array([[184, 180],
       [ 72,  76]])

In [87]:
np.dot(m1,m1)

array([[184, 180],
       [ 72,  76]])

In [120]:
np.linalg.matrix_power(m1,0)

array([[1, 0],
       [0, 1]])

In [121]:
np.linalg.matrix_power(m1,-2)

array([[ 0.07421875, -0.17578125],
       [-0.0703125 ,  0.1796875 ]])

In [122]:
m8 = np.linalg.inv(m1)

In [123]:
m8

array([[ 0.1875, -0.3125],
       [-0.125 ,  0.375 ]])

In [92]:
np.linalg.matrix_power(m8,2)

array([[ 0.07421875, -0.17578125],
       [-0.0703125 ,  0.1796875 ]])

In [125]:
# consider a linear equation with two variable
# 3x+y=9
# x+2y=8

In [126]:
l1 = np.array([[3,1],[1,2]])
l1

array([[3, 1],
       [1, 2]])

In [129]:
l2 = np.array([9,8])
l2

array([9, 8])

In [131]:
np.linalg.solve(l1,l2)   #TO SOLVE vALUES 

array([2., 3.])

In [97]:
# consider a linear equation with three variable

In [134]:
l3 = np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
l3


array([[ 6,  2, -5],
       [ 3,  3, -2],
       [ 7,  5, -3]])

In [135]:
l4 = np.array([13,13,26])
l4

array([13, 13, 26])

In [136]:
np.linalg.solve(l3,l4)

array([2., 3., 1.])

In [100]:
# determinant of a matrix (.det())

In [137]:
d1 = np.array([[1,2],[3,4]])
d1

array([[1, 2],
       [3, 4]])

In [102]:
np.linalg.det(d1)

-2.0000000000000004

In [103]:
round(np.linalg.det(d1)) #used to round up value

-2

In [104]:
d2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [105]:
d2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
np.linalg.det(d2)

0.0

In [107]:
round(np.linalg.det(d2))

0

In [108]:
# identity matrix

In [109]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x=