# sPyd3R

In [1]:
import numpy as np

In [2]:
newarr=np.array([1,2,3,4],np.int8)

In [3]:
newarr

array([1, 2, 3, 4], dtype=int8)

In [4]:
newarr=np.array([1,25512545242,3,4],np.int64)

In [5]:
newarr=np.array([1,25512545242,3,4],np.int64)

In [6]:
newarr

array([          1, 25512545242,           3,           4], dtype=int64)

In [7]:
newarr.shape

(4,)

In [8]:
new2d=np.array([[1,2,3,4]])

In [9]:
new2d[0][1]

2

In [10]:
newarr.shape

(4,)

In [11]:
new2d.shape

(1, 4)

# Array Creation : Conversion From Other Python Structures

In [12]:
list2darr=np.array([[1,2,3],[4,5,6],[6,7,8]])

In [13]:
list2darr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
list2darr.size
list2darr.shape

(3, 3)

In [15]:
list2darr.size

9

In [16]:
import numpy as np

In [17]:
zer=np.zeros((2,5))

In [18]:
zer

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zer.dtype

dtype('float64')

In [20]:
zer.shape

(2, 5)

In [21]:
zer.size

10

In [22]:
rndarr=np.arange(1,6)

In [23]:
rndarr

array([1, 2, 3, 4, 5])

In [24]:
lspac=np.linspace(1,50,10)

In [25]:
lspac

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [26]:
emp=np.empty((2,8))

In [27]:
emp

array([[            nan, 1.69121096e-306, 3.22646744e-307,
        2.67022953e-307, 4.22790856e-307, 8.34441742e-308,
        1.78022342e-306, 6.23058028e-307],
       [9.79107872e-307, 6.89807188e-307, 7.56594375e-307,
        6.23060065e-307, 1.78021527e-306, 8.34454050e-308,
        1.11261027e-306, 1.11253693e-306]])

In [28]:
emp_lin=np.empty_like(emp)

In [29]:
emp_lin

array([[4.67296746e-307, 1.69121096e-306, 3.22646744e-307,
        2.67022953e-307, 4.22790856e-307, 8.34441742e-308,
        1.78022342e-306, 6.23058028e-307],
       [9.79107872e-307, 6.89807188e-307, 7.56594375e-307,
        6.23060065e-307, 1.78021527e-306, 8.34454050e-308,
        1.11261027e-306, 2.04712907e-306]])

In [30]:
ide=np.identity(49)

In [31]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [32]:
ide.shape
ide.size

2401

In [33]:
ide.shape

(49, 49)

In [34]:
arr=np.arange(20)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
arr.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
arr=arr.reshape(2,10)

In [39]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [40]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [41]:
ar=np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
ar.sum(axis=0)

array([12, 15, 18])

In [44]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [45]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
ar.flat

In [47]:
for i in ar:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [48]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [49]:
ar.ndim

2

In [50]:
ar.nbytes

36

In [51]:
ars=np.array([1,2,43,1212,21123,123,321123,23])

In [52]:
ars.argmax()

6

In [53]:
ars.argmin()

0

In [54]:
ars.argsort()

array([0, 1, 7, 2, 5, 3, 4, 6], dtype=int64)

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
ar.argmin()

0

In [57]:
ar.argmax()

8

In [58]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [59]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [60]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [61]:
ar.argmax()

8

In [62]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [63]:
ars.argsort(axis=0)

array([0, 1, 7, 2, 5, 3, 4, 6], dtype=int64)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
ar=np.arange(10)

In [66]:
ar=[[1,2,3],
   [4,5,6],[7,1,0]]

In [67]:
ar

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [68]:
ar=np.array(ar)

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [71]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [72]:
ar2=np.array([[1,2,3],
   [4,5,6],[7,1,0]])

In [73]:
ar+ar2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [74]:
import sys

In [75]:
py_arr=[0,4,5,4]

In [76]:
np_ar=np.array(py_arr)

In [77]:
sys.getsizeof(1) * len(py_arr)

112

In [78]:
np_ar.itemsize * np_ar.size

16

# Pandas Started 

In [1]:
import pandas as pd
import numpy as np

In [2]:
dict={
    "name":['harry' , 'rohan' , 'joshi' , 'pant'],
    "mrks":[45,54,98,34],
    "city" : ['rampur','kichha' , 'lalkuan','hldwani']
}

In [3]:
df=pd.DataFrame(dict)

In [4]:
df

name  mrks     city
0  harry    45   rampur
1  rohan    54   kichha
2  joshi    98  lalkuan
3   pant    34  hldwani

In [5]:
pd.series('name':)

SyntaxError: invalid syntax (<ipython-input-5-c20b71538f9a>, line 1)

In [83]:
df.head(2)

name  mrks    city
0  harry    45  rampur
1  rohan    54  kichha

In [84]:
df.tail(2)

name  mrks     city
2  joshi    98  lalkuan
3   pant    34  hldwani

In [85]:
df.describe()

mrks
count   4.000000
mean   57.750000
std    28.052035
min    34.000000
25%    42.250000
50%    49.500000
75%    65.000000
max    98.000000

In [86]:
ser=pd.Series(np.random.rand(34))

In [87]:
ser

0     0.952013
1     0.003981
2     0.371459
3     0.633832
4     0.527408
5     0.447680
6     0.476213
7     0.390828
8     0.494072
9     0.975075
10    0.116342
11    0.340738
12    0.699083
13    0.083328
14    0.114228
15    0.663469
16    0.471793
17    0.573937
18    0.786939
19    0.353334
20    0.014544
21    0.012934
22    0.593432
23    0.153950
24    0.065269
25    0.781479
26    0.154955
27    0.364656
28    0.257602
29    0.604270
30    0.656063
31    0.667136
32    0.704197
33    0.711745
dtype: float64

In [88]:
type(ser)

pandas.core.series.Series

In [89]:
newdfr=pd.DataFrame(np.random.rand(324,5) , index=np.arange(324))

In [90]:
newdfr

0         1         2         3         4
0    0.475402  0.074725  0.769956  0.809064  0.479748
1    0.121397  0.112844  0.013384  0.124312  0.499591
2    0.107165  0.606811  0.627643  0.236387  0.865125
3    0.280728  0.745549  0.469345  0.152157  0.874567
4    0.756279  0.486956  0.419664  0.120831  0.061562
..        ...       ...       ...       ...       ...
319  0.436977  0.142842  0.710917  0.979503  0.181976
320  0.475452  0.313349  0.688489  0.740646  0.222830
321  0.654157  0.281276  0.023933  0.578608  0.338848
322  0.547127  0.090956  0.253530  0.430923  0.656542
323  0.776921  0.323064  0.200719  0.151795  0.672939

[324 rows x 5 columns]

In [91]:
type(newdfr)

pandas.core.frame.DataFrame

In [92]:
dsf=np.arange(50)

In [93]:
dsf

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [94]:
dsf=dsf.reshape(10,5)

In [95]:
dsf

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [96]:
dsf.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [97]:
dsf

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [98]:
dsf.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [99]:
df.sort_index()

name  mrks     city
0  harry    45   rampur
1  rohan    54   kichha
2  joshi    98  lalkuan
3   pant    34  hldwani

In [100]:
df.sort_index(axis=0,ascending=False)

name  mrks     city
3   pant    34  hldwani
2  joshi    98  lalkuan
1  rohan    54   kichha
0  harry    45   rampur

In [101]:
df

name  mrks     city
0  harry    45   rampur
1  rohan    54   kichha
2  joshi    98  lalkuan
3   pant    34  hldwani

In [102]:
newdf2=dsf

In [103]:
newdf2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [104]:
newdf2[0][0]=214521

In [105]:
dsf

array([[214521,      1,      2,      3,      4],
       [     5,      6,      7,      8,      9],
       [    10,     11,     12,     13,     14],
       [    15,     16,     17,     18,     19],
       [    20,     21,     22,     23,     24],
       [    25,     26,     27,     28,     29],
       [    30,     31,     32,     33,     34],
       [    35,     36,     37,     38,     39],
       [    40,     41,     42,     43,     44],
       [    45,     46,     47,     48,     49]])

In [106]:
newdf2

array([[214521,      1,      2,      3,      4],
       [     5,      6,      7,      8,      9],
       [    10,     11,     12,     13,     14],
       [    15,     16,     17,     18,     19],
       [    20,     21,     22,     23,     24],
       [    25,     26,     27,     28,     29],
       [    30,     31,     32,     33,     34],
       [    35,     36,     37,     38,     39],
       [    40,     41,     42,     43,     44],
       [    45,     46,     47,     48,     49]])

In [107]:
df

name  mrks     city
0  harry    45   rampur
1  rohan    54   kichha
2  joshi    98  lalkuan
3   pant    34  hldwani

In [108]:
newdf2.shape

(10, 5)

In [109]:
newdf2

array([[214521,      1,      2,      3,      4],
       [     5,      6,      7,      8,      9],
       [    10,     11,     12,     13,     14],
       [    15,     16,     17,     18,     19],
       [    20,     21,     22,     23,     24],
       [    25,     26,     27,     28,     29],
       [    30,     31,     32,     33,     34],
       [    35,     36,     37,     38,     39],
       [    40,     41,     42,     43,     44],
       [    45,     46,     47,     48,     49]])

In [110]:
df

name  mrks     city
0  harry    45   rampur
1  rohan    54   kichha
2  joshi    98  lalkuan
3   pant    34  hldwani

In [111]:
df.columns=list("ABC")

In [112]:
df

A   B        C
0  harry  45   rampur
1  rohan  54   kichha
2  joshi  98  lalkuan
3   pant  34  hldwani

In [113]:
df.loc[0,0]=5445

In [114]:
df

A   B        C       0
0  harry  45   rampur  5445.0
1  rohan  54   kichha     NaN
2  joshi  98  lalkuan     NaN
3   pant  34  hldwani     NaN

In [115]:
df.loc[0,'A']=45758

In [116]:
df

A   B        C       0
0  45758  45   rampur  5445.0
1  rohan  54   kichha     NaN
2  joshi  98  lalkuan     NaN
3   pant  34  hldwani     NaN

In [117]:
df=df.drop(0,axis=1)

In [118]:
df

A   B        C
0  45758  45   rampur
1  rohan  54   kichha
2  joshi  98  lalkuan
3   pant  34  hldwani

In [119]:
df.loc[[1,2] , ['B','C']]

B        C
1  54   kichha
2  98  lalkuan

In [120]:
df.loc[[1,2],:]

A   B        C
1  rohan  54   kichha
2  joshi  98  lalkuan

In [121]:
df.loc[:,['A','B','C']]

A   B        C
0  45758  45   rampur
1  rohan  54   kichha
2  joshi  98  lalkuan
3   pant  34  hldwani

In [122]:
df.to_csv('joshi.csv') #To save as (.csv) File

In [123]:
df.iloc[0,2]

'rampur'

In [124]:
df

A   B        C
0  45758  45   rampur
1  rohan  54   kichha
2  joshi  98  lalkuan
3   pant  34  hldwani

In [125]:
df.iloc[[1,2],[0,2]]

A        C
1  rohan   kichha
2  joshi  lalkuan

In [126]:
df

A   B        C
0  45758  45   rampur
1  rohan  54   kichha
2  joshi  98  lalkuan
3   pant  34  hldwani

In [134]:
df.loc[: ,'B']='New_val'

In [135]:
df

A        B        C
0  45758  New_val   rampur
1  rohan  New_val   kichha
2  joshi  New_val  lalkuan
3   pant  New_val  hldwani

In [147]:
dfk=pd.DataFrame({
    "name":['Alfred','Batman','Catman'],
    "toy":[np.nan,'Batmobile','Bullwhip'],
    "born":['121','12123',np.nan]
})

In [148]:
dfk

name        toy   born
0  Alfred        NaN    121
1  Batman  Batmobile  12123
2  Catman   Bullwhip    NaN

In [149]:
dfk.dropna()        #Will drop Na

name        toy   born
1  Batman  Batmobile  12123

In [152]:
dfk.dropna(how='all',axis=1)

name        toy   born
0  Alfred        NaN    121
1  Batman  Batmobile  12123
2  Catman   Bullwhip    NaN

In [153]:
dfk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   toy     2 non-null      object
 2   born    2 non-null      object
dtypes: object(3)
memory usage: 200.0+ bytes


In [154]:
dfk.isnull()

name    toy   born
0  False   True  False
1  False  False  False
2  False  False   True

In [155]:
dfk.notnull()

name    toy   born
0  True  False   True
1  True   True   True
2  True   True  False

In [188]:
dicts={
    "r1":['hdws' , 'wdwohan' , 'joshi' , 'pant'],
    "mks":[45,54,98,34],
    "cty" : ['rampur','kichha' , 'lalkuan','hldwani']
}

In [189]:
nw=pd.DataFrame(dicts)

TypeError: 'dict' object is not callable

In [ ]:
print("Username And Domain Seprator")
print("Enter Email")
mail=input(">>")
flag=0
for i in mail:
    if(i=='@'):
        username = mail.split('@')

        print(f"Username: {username[0]}")

        print(f"domain: {username[1]}")

        
        

if(flag!=1):
    print("You Have Entered Wrong Email")


In [20]:
f=open("workfile.txt",'r')
line=f.read()
print(line)
f.close()

 new line 



In [21]:
f=open("workfile.txt",'r')
for line in f:
        print(line,end=" ")
f.close()

 new line 
 

In [19]:
f=open("workfile.txt",'w')
f.write(" new line \n")
f.close()

In [5]:
import numpy as np
l=[1,2,3,4,5]
n1=np.array([l])

In [6]:
n1

array([[1, 2, 3, 4, 5]])

In [7]:


n1=n.column_vstack()
n1

NameError: name 'n' is not defined

In [10]:
import numpy as np
n1=np.array([10,20,30])
n1=n1+1
n1


array([11, 21, 31])

In [14]:
np.mean(n1)


21.0

In [15]:
np.median(n1)

21.0

In [16]:
np.std(n1)

8.16496580927726

In [18]:
n2=[13,21,3123,12312,123]
n2

[13, 21, 3123, 12312, 123]

In [22]:
np.save('myfilenamesds.ipynb',n2) #for saving a file in our system 

In [23]:
np.intersect1d(n1,n2)

array([21])

In [6]:
import pandas as pd

In [7]:
s1=pd.Series([1,2,3,4,5])

In [8]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
type(s1)

pandas.core.series.Series

In [10]:
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [12]:
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [18]:
pd.Series({'k1':10,'k2':20,'k3':30},index=['k1','k2','k3'])

k1    10
k2    20
k3    30
dtype: int64

In [22]:
s2=pd.Series([1,2,3,4])
s2

0    1
1    2
2    3
3    4
dtype: int64

In [23]:
pd.DataFrame({"Name":['A','B','C'] , "Marks":[50,60,70]})

Name  Marks
0    A     50
1    B     60
2    C     70

In [30]:
iris=pd.read_csv('iris.csv')

In [32]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
iris.tail()

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [35]:
iris.shape

(150, 5)

In [36]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [39]:
iris.iloc[0:3,0:4] 
#displays rows and columns 

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [46]:
iris.iloc[6:,2:]

petal_length  petal_width    species
6             1.4          0.3     setosa
7             1.5          0.2     setosa
8             1.4          0.2     setosa
9             1.5          0.1     setosa
10            1.5          0.2     setosa
..            ...          ...        ...
145           5.2          2.3  virginica
146           5.0          1.9  virginica
147           5.2          2.0  virginica
148           5.4          2.3  virginica
149           5.1          1.8  virginica

[144 rows x 3 columns]

In [47]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [49]:
iris.iloc[0:15 , 2:4:2]

petal_length
0            1.4
1            1.4
2            1.3
3            1.5
4            1.4
5            1.7
6            1.4
7            1.5
8            1.4
9            1.5
10           1.5
11           1.6
12           1.4
13           1.1
14           1.2

In [50]:
iris.drop('petal_length' , axis=1)

sepal_length  sepal_width  petal_width    species
0             5.1          3.5          0.2     setosa
1             4.9          3.0          0.2     setosa
2             4.7          3.2          0.2     setosa
3             4.6          3.1          0.2     setosa
4             5.0          3.6          0.2     setosa
..            ...          ...          ...        ...
145           6.7          3.0          2.3  virginica
146           6.3          2.5          1.9  virginica
147           6.5          3.0          2.0  virginica
148           6.2          3.4          2.3  virginica
149           5.9          3.0          1.8  virginica

[150 rows x 4 columns]

In [58]:
iris.loc[1,0]=34343
iris

sepal_length  sepal_width  petal_length  petal_width    species        0
0             5.1          3.5           1.4          0.2     setosa  34343.0
1         34343.0          3.0           1.4          0.2     setosa  34343.0
2             4.7          3.2           1.3          0.2     setosa      NaN
3             4.6          3.1           1.5          0.2     setosa      NaN
4             5.0          3.6           1.4          0.2     setosa      NaN
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica      NaN
146           6.3          2.5           5.0          1.9  virginica      NaN
147           6.5          3.0           5.2          2.0  virginica      NaN
148           6.2          3.4           5.4          2.3  virginica      NaN
149           5.9          3.0           5.1          1.8  virginica      NaN

[150 rows x 6 columns]

In [65]:
iris.drop([2 , 3  , 1],axis=0)

sepal_length  sepal_width  petal_length  petal_width    species        0
0             5.1          3.5           1.4          0.2     setosa  34343.0
5             5.4          3.9           1.7          0.4     setosa      NaN
7             5.0          3.4           1.5          0.2     setosa      NaN
9             4.9          3.1           1.5          0.1     setosa      NaN
10            5.4          3.7           1.5          0.2     setosa      NaN
..            ...          ...           ...          ...        ...      ...
145           6.7          3.0           5.2          2.3  virginica      NaN
146           6.3          2.5           5.0          1.9  virginica      NaN
147           6.5          3.0           5.2          2.0  virginica      NaN
148           6.2          3.4           5.4          2.3  virginica      NaN
149           5.9          3.0           5.1          1.8  virginica      NaN

[144 rows x 6 columns]

In [66]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species        0
0           5.1          3.5           1.4          0.2  setosa  34343.0
1       34343.0          3.0           1.4          0.2  setosa  34343.0
2           4.7          3.2           1.3          0.2  setosa      NaN
3           4.6          3.1           1.5          0.2  setosa      NaN
5           5.4          3.9           1.7          0.4  setosa      NaN

In [75]:
i1=iris.drop(('sepal_length') ,axis=1)
i1

sepal_width  petal_length  petal_width    species        0
0            3.5           1.4          0.2     setosa  34343.0
1            3.0           1.4          0.2     setosa  34343.0
2            3.2           1.3          0.2     setosa      NaN
3            3.1           1.5          0.2     setosa      NaN
5            3.9           1.7          0.4     setosa      NaN
..           ...           ...          ...        ...      ...
145          3.0           5.2          2.3  virginica      NaN
146          2.5           5.0          1.9  virginica      NaN
147          3.0           5.2          2.0  virginica      NaN
148          3.4           5.4          2.3  virginica      NaN
149          3.0           5.1          1.8  virginica      NaN

[147 rows x 5 columns]

In [76]:
def fun(s):
    return s*2

In [77]:
iris[['sepal_length' , 'petal_length']].apply(fun)

sepal_length  petal_length
0            10.2           2.8
1         68686.0           2.8
2             9.4           2.6
3             9.2           3.0
5            10.8           3.4
..            ...           ...
145          13.4          10.4
146          12.6          10.0
147          13.0          10.4
148          12.4          10.8
149          11.8          10.2

[147 rows x 2 columns]

In [78]:
iris['species'].value_counts()

versicolor    50
virginica     50
setosa        47
Name: species, dtype: int64

In [80]:
i2=iris.sort_values(by='petal_width')
i2

sepal_length  sepal_width  petal_length  petal_width    species   0
34            4.9          3.1           1.5          0.1     setosa NaN
32            5.2          4.1           1.5          0.1     setosa NaN
37            4.9          3.1           1.5          0.1     setosa NaN
9             4.9          3.1           1.5          0.1     setosa NaN
12            4.8          3.0           1.4          0.1     setosa NaN
..            ...          ...           ...          ...        ...  ..
136           6.3          3.4           5.6          2.4  virginica NaN
114           5.8          2.8           5.1          2.4  virginica NaN
144           6.7          3.3           5.7          2.5  virginica NaN
100           6.3          3.3           6.0          2.5  virginica NaN
109           7.2          3.6           6.1          2.5  virginica NaN

[147 rows x 6 columns]